apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ../base

patchesStrategicMerge:
  - booking-holds-ttl-env.yaml

secretGenerator:
- name: secrets-env
  envs:
  - .env

- name: config-files
  files:
  - rsa.public.key
